-- AUDITORIA

-- EJ 1
DROP TABLE auditoria

CREATE TABLE auditoria(
	auditID INTEGER IDENTITY(1,1) PRIMARY KEY,
	nombreTabla VARCHAR(30) NOT NULL,
	operacion CHAR(1) CHECK (operacion IN ('I','O','N','D')),
	rowData VARCHAR(255) NOT NULL,
	usuario VARCHAR(30) DEFAULT SUSER_NAME(),
	fecha DATE DEFAULT GETDATE()
)

-- EJ 2

CREATE PROCEDURE altaAuditoria(@NOMBRE_TABLA VARCHAR(30), @OPERACION CHAR(1), @ROWDATA VARCHAR(30))
AS
BEGIN
	
	INSERT INTO auditoria(nombreTabla, operacion, rowData)
	VALUES (@NOMBRE_TABLA, @OPERACION, @ROWDATA)

END

-- EJ 3

CREATE TRIGGER insertAuditoria
ON manufact
AFTER INSERT
AS
BEGIN
	
	DECLARE @MANU_CODE CHAR(3), @MANU_NAME VARCHAR(15), @LEADTIME SMALLINT
	DECLARE @ROWDATE NVARCHAR(100)

	DECLARE C_AUDITORIA CURSOR FOR
	SELECT i.manu_code, i.manu_name, i.lead_time FROM inserted i

	OPEN C_AUDITORIA
	FETCH NEXT FROM C_AUDITORIA INTO @MANU_CODE, @MANU_NAME, @LEADTIME
	WHILE(@@FETCH_STATUS = 0)
	BEGIN
		SET @ROWDATE = @MANU_CODE + '|' + @MANU_NAME + '|' + CONVERT(NVARCHAR(10),@LEADTIME)
		EXEC dbo.altaAuditoria 'manufact','I',@ROWDATE 
		FETCH NEXT FROM C_AUDITORIA INTO @MANU_CODE, @MANU_NAME, @LEADTIME
	END

	CLOSE C_AUDITORIA
	DEALLOCATE C_AUDITORIA

END

-- EJ 4

CREATE TRIGGER borradoManufact
ON manufact
AFTER DELETE
AS
BEGIN
	
	DECLARE @MANU_CODE CHAR(3), @MANU_NAME VARCHAR(15), @LEADTIME SMALLINT
	DECLARE @ROWDATE NVARCHAR(100)

	DECLARE C_MANUFACT CURSOR FOR
	SELECT d.manu_code, d.manu_name, d.lead_time FROM deleted d

	OPEN C_MANUFACT
	FETCH NEXT FROM C_MANUFACT INTO @MANU_CODE, @MANU_NAME, @LEADTIME
	WHILE(@@FETCH_STATUS = 0)
	BEGIN
		SET @ROWDATE = @MANU_CODE + '|' + @MANU_NAME + '|' + CONVERT(NVARCHAR(10),@LEADTIME)
		EXEC dbo.altaAuditoria 'manufact','D',@ROWDATE 
		FETCH NEXT FROM C_MANUFACT INTO @MANU_CODE, @MANU_NAME, @LEADTIME
	END

	CLOSE C_MANUFACT
	DEALLOCATE C_MANUFACT

END

-- EJ 5	

CREATE TRIGGER updateManufact
ON manufact
AFTER UPDATE
AS
BEGIN
	
	DECLARE @MANU_CODE CHAR(3), @MANU_NAME_O VARCHAR(15), @LEADTIME_O SMALLINT
	DECLARE @ROWDATE NVARCHAR(100), @MANU_NAME_N VARCHAR(15), @LEADTIME_N SMALLINT

	DECLARE C_MANUFACT CURSOR FOR
	SELECT d.manu_code, d.manu_name, d.lead_time, i.manu_name, i.lead_time FROM deleted d
	JOIN inserted i ON i.manu_code = d.manu_code

	OPEN C_MANUFACT
	FETCH NEXT FROM C_MANUFACT INTO @MANU_CODE, @MANU_NAME_O, @LEADTIME_O, @MANU_NAME_N, @LEADTIME_N
	WHILE(@@FETCH_STATUS = 0)
	BEGIN
		SET @ROWDATE = @MANU_CODE + '|' + @MANU_NAME_O + '|' + CONVERT(NVARCHAR(10),@LEADTIME_O)
		EXEC dbo.altaAuditoria 'manufact','D',@ROWDATE
		SET @ROWDATE = @MANU_CODE + '|' + @MANU_NAME_N + '|' + CONVERT(NVARCHAR(10),@LEADTIME_N)
		EXEC dbo.altaAuditoria 'manufact','N',@ROWDATE
		FETCH NEXT FROM C_MANUFACT INTO @MANU_CODE, @MANU_NAME_O, @LEADTIME_O, @MANU_NAME_N, @LEADTIME_N
	END

	CLOSE C_MANUFACT
	DEALLOCATE C_MANUFACT

END

-- EJ 6

DELETE FROM manufact WHERE manu_code = 'XXX'

INSERT INTO manufact(manu_code, manu_name, lead_time)
VALUES('XXX', 'Xtra large', 23)

UPDATE manufact SET manu_name = 'Extra Large' WHERE manu_code = 'XXX'

SELECT * FROM auditoria

INSERT INTO manufact(manu_code, manu_name, lead_time)
VALUES('XXX', 'Xtra large', 23)

INSERT INTO manufact(manu_code, manu_name, lead_time)
VALUES('ZZZ', 'Zampini SA', 11)

DELETE FROM manufact WHERE manu_code = 'ZZZ'

SELECT * FROM auditoria

